target: patch_flow.trainer.LatentPatchForcingTrainer

params:
  model: ${oc.select:model, null}
  first_stage: ${oc.select:autoencoder, null}
  
  # patch flow forcing
  flow:
    target: patch_flow.flow_pf.PatchFlowForcing
    params:
      patch_size: 2
      timestep_sampler:
        target: patch_flow.timestep_schedules.LogitNormalTruncatedGaussian
        params:
          std: 0.6
          loc: 0.7
          scale: 1.0

  # learning
  lr: 1e-4
  weight_decay: 0.0
  ema_rate: 0.9999
  lr_scheduler_cfg: ${oc.select:lr_scheduler, null}

  # sampling
  sample_kwargs:
    num_steps: 50
    progress: False