target: patch_flow.models.pf_transformer.PatchForcingDiT
params:
  in_channels: 4
  input_size: 32
  depth: 12
  hidden_size: 768
  patch_size: 2
  num_heads: 12
  num_classes: 1000
  compile: true
  predict_uncertainty: true